site_name: option_pricing
site_url: https://willemk-stack.github.io/option-pricing-library/
repo_url: https://github.com/willemk-stack/option-pricing-library
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material

plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: user_guides/quickstart.md
  - User guides:
      - Black–Scholes: user_guides/black_scholes.md
      - Monte Carlo: user_guides/monte_carlo.md
      - Binomial CRR: user_guides/binomial_crr.md
      - Diagnostics: user_guides/diagnostics.md
  - API: api.md
  - Notes:
      - Black–Scholes pricing: notes/bs_pricing.md
      - GBM: notes/gbm.md
      - Monte Carlo: notes/mc.md
      - Binomial CRR: notes/binomial_crr.md
      - Brownian motion and Itô: notes/brownian_motion_and_Ito.md
